name = "RegularizationTools"
uuid = "29dad682-9a27-4bc3-9c72-016788665182"
authors = ["Markus Petters"]
version = "0.4.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MatrixDepot = "b51810bb-c9f3-55da-ae3c-350fc1fbce05"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Underscores = "d9a01c3f-67ce-4d8c-9b55-35f6e4050bb1"

[compat]
Calculus = "0.5.0 - 0.5.1"
Lazy = "0.13 - 0.15"
LeastSquaresOptim = "0.7.0 - 0.7.6, 0.8"
MLStyle = "0.4.6"
MatrixDepot = "0.8, 1.0"
Memoize = "0.4"
Optim = "0.18.0 - 0.22.0, 1.2"
Underscores = "2.0.0"
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
